// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjJiyPM1oFC3HD81sApv44YvmMP5Ozulk',
    appId: '1:234931871933:web:89c4bb01df393772ff57d4',
    messagingSenderId: '234931871933',
    projectId: 'assessment3-adam-fahrin',
    authDomain: 'assessment3-adam-fahrin.firebaseapp.com',
    databaseURL: 'https://assessment3-adam-fahrin-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'assessment3-adam-fahrin.firebasestorage.app',
    measurementId: 'G-PNFL0KNCP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD2KskZQxGOH84kNFajGII_EQ-11b38FY',
    appId: '1:234931871933:android:89f4ed4b56d2874eff57d4',
    messagingSenderId: '234931871933',
    projectId: 'assessment3-adam-fahrin',
    databaseURL: 'https://assessment3-adam-fahrin-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'assessment3-adam-fahrin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGzwnuzD36AIKuBWVD356S7-RV40YZorA',
    appId: '1:234931871933:ios:88e90ad9594ac763ff57d4',
    messagingSenderId: '234931871933',
    projectId: 'assessment3-adam-fahrin',
    databaseURL: 'https://assessment3-adam-fahrin-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'assessment3-adam-fahrin.firebasestorage.app',
    iosBundleId: 'com.example.jm264a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGzwnuzD36AIKuBWVD356S7-RV40YZorA',
    appId: '1:234931871933:ios:88e90ad9594ac763ff57d4',
    messagingSenderId: '234931871933',
    projectId: 'assessment3-adam-fahrin',
    databaseURL: 'https://assessment3-adam-fahrin-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'assessment3-adam-fahrin.firebasestorage.app',
    iosBundleId: 'com.example.jm264a',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjJiyPM1oFC3HD81sApv44YvmMP5Ozulk',
    appId: '1:234931871933:web:e00e33982f5baf19ff57d4',
    messagingSenderId: '234931871933',
    projectId: 'assessment3-adam-fahrin',
    authDomain: 'assessment3-adam-fahrin.firebaseapp.com',
    databaseURL: 'https://assessment3-adam-fahrin-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'assessment3-adam-fahrin.firebasestorage.app',
    measurementId: 'G-V6W7XDPBYE',
  );
}
